### ISSUE TITLE
Completely remove node-red-contrib-xterm 

### ISSUE THREAD

**Issue by Paul-Reed** [bartbutenaers/node-red-contrib-xterm#21]
How do we completely remove node-red-contrib-xterm from our servers?

Using the palette - the node is always in use therefore cannot be removed.
Removing it by using the command prompt - `npm uninstall node-red-contrib-xterm` removed the node, but then node-RED will not restart;
```
17 Dec 09:47:13 - [info] Waiting for missing types to be registered:
17 Dec 09:47:13 - [info]  - xterm_config
```

**Comment by bartbutenaers** [comment]
Hi Paul,
That is indeed a special case, similar to all other nodes with a sidebar panel.  Every property value that you enter in the sidebar panel, will be stored in a config node:  
+ When you delete that config node, the sidebar panel will (in every code snippet where it needs that config node) automatically create a new config node.
+ In fact only the sidebar panel uses that config node.  Since no others use the config node, it would end up as an "unused" config node.  To avoid that, the config nodes for sidebar panels use a little trick: they always return "used", to make sure our users don't remove them by accident...

So you need to remove the ("used") xterm config node.
Bart

**Comment by Paul-Reed** [comment]
Thanks Bart, yes, removing the config node enabled me to remove it OK.
