### ISSUE TITLE
is a password possible with this node?

### ISSUE THREAD

**Issue by houser42** [bartbutenaers/node-red-contrib-xterm#25]
Hello,
I am testing this promising node for remote terminal access to a linux box, a beagle bone.
It is running Node Red under Venus OS and SSH access works locally with the password I can set.

Attempting to do sudo commands via this node gives me "sorry try again" when typing the same password.

Is there a trick or is this not possible?
Many thanks for any hints.

**Comment by bartbutenaers** [comment]
Hi @houser42,

I haven't tried yet that scenario.  But this node is quite unmaintained, so its [dependencies](https://github.com/bartbutenaers/node-red-contrib-xterm/blob/master/package.json#L5) have become obsolete:
+ The [xterm ](https://www.npmjs.com/package/xterm) library is abandonned and should be replaced by the successor [@xterm/xterm](https://www.npmjs.com/package/@xterm/xterm).
+ The [node-pty-prebuilt-multiarch](https://www.npmjs.com/package/node-pty-prebuilt-multiarch) library hasn't maintained over 2 years anymore, and should be replaced by [@homebridge/node-pty-prebuilt-multiarch](https://www.npmjs.com/package/@homebridge/node-pty-prebuilt-multiarch)

Which means a lot of refactoring work...
But I don't have time to do that, because I need to migrate all my ui nodes for dashboard D2...

Bart

**Comment by houser42** [comment]
Understood. Appreciate the heads-up!
